displayName: Authorization header conversion
type: middleware

import: github.com/Lightirius/traefik-auth-converter

summary: Converts between Basic, Beared and Digest authorization header with optional base64 encoding\decoding

testData:
  tokenSource: "password"
  encodeToken: true
  sourceType: "Basic"
  targetType: "Bearer"
